### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document'

### ISSUE THREAD

**Issue by invaders-xx** [GuavaCZ/tutorials#5]
I created a tutorial using latest version :

```php
public function tutorial(Tutorial $tutorial): Tutorial
    {
        return $tutorial->steps([
            Step::make('.page-layout-action')
                ->label(__('Page layout')),
        ]);
    }
```
and I have an action button on the page with class 'page-layout-action'
and I get this console error :

`step.js:209 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#data..page-layout-action' is not a valid selector.`

Did I miss smth ?

**Comment by fsamapoor** [comment]
Hey @invaders-xx,

I was able to select the HTML elements using the `Selector::make()` selector.

[Lukas has given an example himself](https://github.com/GuavaCZ/tutorials/issues/4#issuecomment-2025930482), but it seems like this is undocumented in the readme file.

Like this:
```php
Step::make(Selector::make('.fi-sidebar-item:has(a[href*="scores"])'))
```

**Comment by lukas-frey** [comment]
Hi, thanks a lot for noticing the issue in the documentation.
