### ISSUE TITLE
I messed something?

### ISSUE THREAD

**Issue by mrozek90** [GuavaCZ/tutorials#7]
Hi,

what I doing wrong?
Fresh Laravel 10 + Filament 3.2.

![Zrzut ekranu z 2024-05-25 21-14-03](https://github.com/GuavaCZ/tutorials/assets/80465686/f4ea98c0-e568-49d1-9ef8-1eaf5d4494d1)
![Zrzut ekranu z 2024-05-25 21-13-53](https://github.com/GuavaCZ/tutorials/assets/80465686/c91c441d-32be-4ee6-b345-d711c357c138)

**Comment by lukas-frey** [comment]
Make sure you followed this: https://github.com/GuavaCZ/tutorials?tab=readme-ov-file#add-assets-to-your-theme

**Comment by mrozek90** [comment]
ok... my bad.

I edited tailwind.config.js in root folder not in custom theme folder... 

sorry :)
